version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - "postgres:aal_db"
    working_dir: /app

  postgres:
    build: docker_postgres/.
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${ALL_DATABASE_PASSWORD}
      - POSTGRES_USER=${ALL_DATABASE_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
